/**:
  ros__parameters:
    link_layer: "ethernet" # "ethernet" | "cube-evk" | "cohda"
    target_device: "lo" # Should be the IP address of the target device or the network interface name
    gps_method: "ros" # "ros" | "gpsd"
    gps_provider: "/sensing/gnss/gps" # ros topic or gpsd server (ip:port)
    is_sender: true
    publish_own_cams: false
    cam_enabled: true
    cpm_enabled: false
    security: "none"
    certificate: ""
    certificate-key: ""
    certificate-chain:
      - ""
