/**:
  ros__parameters:
    link_layer: "cube-evk"
    network_interface: "v2x_testing"
    cube_ip: "192.168.94.84"
    is_sender: true
    publish_own_cams: false
    security: "none"
    certificate: ""
    certificate-key: ""
    certificate-chain:
      - ""
